# Generated by Django 3.2.12 on 2022-06-08 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('common_interest', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('total_number', models.IntegerField(blank=True, null=True)),
                ('kakao_chat', models.CharField(blank=True, max_length=50, null=True)),
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
